var itemNameArr = [
    "WD-40 100ml",
    "Clin wiper",
    "Ox bleach",
    "Corrugated hose",
    "Heat-exchange alkali",
    "5L propane tank",
    "M.U.L.E. stimulator",
    "Cocktail Obdolbos",
    "Meldonin",
    "P22",
    "L1 Norepinephrine",
    "SG-C10 Military COFDM",
    "Virtex",
    "VPX Flash Storage Module",
    "UHF RFID Reader",
    "PC CPU",
    "Rechargeable battery",
    "Broken GPhone",
    "A set of tools",
    "Paracord",
    "Powercord",
    "T-Shaped Plug",
    "Graphics card",
    "CPU Fan",
    "Malboro Cigarettes",
    "Strike Cigarettes",
    "Wilston Cigarettes",
    "Wires",
    "Capacitors",
    "Trijicon REAP-IR thermal scope",
    "Polyamide fabric Cordura",
    "Aramid fiber cloth",
    "Ripstop cloth",
    "Electronic components",
    "Fleece cloth",
    "Ushanka ear-flap cap",
    "Cowboy hat",
    "Shemagh (Green)",
    "RayBench Hipster (略)",
    "Round frame sunglasses",
    "Peltor ComTac 2 headset",
    "6B47 Helmet",
    "Fuel conditioner",
    "Antique teapot",
    "Antique vase",
    "Axel parrot figurine",
    "Raven figurine",
    "Bronze lion",
    "Horse figurine",
    "Cat figurine",
    "Golden egg",
    "Wartech gear rig",
    "BlackRock chest rig",
    "KEKTAPE duct tape",
    "Bottle of vodka Tarkovskaya",
    "Bottle of Dan Jackiel Whiskey",
    "Can of beef stew (Large)",
    "Purified water",
    "Bottle of beer Pevko Light",
    "Salty Dog beef sausage",
    "RSP-30 reactive signal cartridge (Green)",
    "BOSS cap",
    "TT Gold",
    "TerraGroup Labs keycard (Blue)",
    "TerraGroup Labs keycard (Green)",
    "Machinery key",
    "Maska-1SCh bulletproof helmet",
    "Bars A-2607 95H18 knife",
    "MP-133 12ga pump-action shotgun",
    "CMS Kit",
    "TerraGroup Labs access keycard",
    "耐久値が50%以下の6B43",
    "Ghost balaclava",
    "BNTI Gzhel-K armor",
    "Ski hat with holes for eyes",
    "Pilgrim tourist backpack",
    "LEDX Skin Transilluminator",
    "Bottle of OLOLO Multivitamins",
    "Pile of meds",
    "Iskra ration pack",
    "Salewa first aid kit",
    "Emelya rye croutons",
    "0.6L water bottle",
    "6L31",
    "Lower half-mask",
    "AK-74N",
    "M4A1",
    "PM pistol",
    "USEC Dogtag",
    "BEAR Dogtag",
    "6-STEN-140-M military battery",
    "OFZ 30x160mm shell",
    "M67 Hand grenade",
    "Gas analyzer",
    "Morphine injector",
    "Car battery",
    "Spark plug",
    "Ophthalmoscope",
    "Gunpowder Kite",
    "Can of beef stew (Small)",
    "",
    "AHF1-M stimulant injector",
    "3-(b-TG) stimulant injector",
    "Key card with a blue marking",
    "Portable defibrillator",
    "BNTI Module-3M body armor",
    "TOZ-106 20ga (略)",
    "Secure Flash drive",
    "Respirator",
    "Medical bloodset",
    "Golden neck chain",
    "Roler submariner gold(略)",
    "SV-98 7.62x54R (略)",
    "Leatherman Multitool",
    "MRE ration pack",
    "Tarcone Director's office key",
    "MS2000 Marker",
    "Portable bunkhouse key",
    "Dorm room 203 key",
    "Dorm room 206 Key",
    "Dorm room 114 Key",
    "",
    "",
    "",
    "RB-KSM key",
    "RB-SMP key",
    "Health Resort west wing room 306 key",
    "Cottage back door key",
    "ZB-014 key",
    "Dorm room 303 key",
    "Military checkpoint key",
    "Gas station storage room key",
    "WIFI Camera",
    "Old firesteel",
    "Evasion armband",
    "Antique axe",
    "Pestily plague mask",
    "Battered antique Book",
    "Shroud half-mask",
    "#FireKlean gun lube",
    "Can of Dr.Lupo's (略)",
    "Golden rooster",
    "42nd Signature (略)",
    "Silver Badge",
    "Veritas guitar pick",
    "Deadlyslob's beard oil",
    "Golden 1GPhone",
    "Can of RatCola",
    "Jar of DevilDog mayo",
    "Loot Lord plushie",
    "Can of sprats",
    "LVNDMARK's rat poison",
    "Fake mustache",
    "Z Wallet",
    "Kotton beanie",
    "Smoke balaclava",
    "Missam forklift key",
    "Video cassette (略)",
    "BakeEzy cook book",
    "JohnB Liquid DNB glasses",
    "Baddie's red beard",
    "DRD body armor",
    "Gingy keychain",
    "Press pass",
    "BEAR Buddy plush toy",
    "Unknown Key",
    "Dorm room 303 key",
    "Trailer park portable cabin key",
    "Dorm room 220 Key",
    "Health Resort west wing office room 112 key",
    "EMERCOM medical unit key",
    "",
    "",
    "",
    "",
    "Cultist's knife",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lv50以上のUSECドックタグ",
    "Lv50以上のBEARドックタグ",
    "Printed circuit board",
    "Signal Jammer",
    "",
    "",
    "",
    "",
    "Radio repeater",
    "AHF1-M (略)",
    "SJ1 TGLabs combat (略)",
    "SJ9 TGLabs combat (略)",
    "SJ6 TGLabs combat (略)",
    "Piece of Plexiglas",
    "Insulating tape",
    "Military circuit board",
    "Working LCD",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "耐久値が50%以下のGzhel",
    "耐久値が50%以上のGzhel",
    "",
    "耐久値が50%以上の6B43",
    "RSP-30 reactive signal cartridge (Yellow)",
    "",
    "",
]